### ISSUE TITLE
Custom fonts not loading 

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/documentation#107]
tested in latest Chrome / Firefox / Safari

![screen shot 2014-12-22 at 14 51 52](https://cloud.githubusercontent.com/assets/39992/5525681/1f324fb4-89ea-11e4-8143-f5c196fde8bd.png)

---

ping when fixed
- [ ] https://twitter.com/anthonyringoet/status/547014424247422976

**Comment by zoepage** [comment]
https://github.com/hoodiehq/documentation/pull/108

**Comment by zoepage** [comment]
fixed. added follow up issue #110
