### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stasberkman** [hoodiehq-archive/documentation#109]
Why i cannot logged in as admin with the password i have set in hoodie start command

**Comment by janl** [comment]
This is a know bug that will be fixed in the next release. In the meantime, when entering the password on the admin login, put double quotes around it, e.g. If your password is `foo` type in `"foo"`.

Thank you for your patience :)

Best

## Jan

**Comment by zoepage** [comment]
@stasberkman can this issue be closed? :)

**Comment by stasberkman** [comment]
Yes thanks
