### ISSUE TITLE
Wrong ports in getting-started-1.md

### ISSUE THREAD

**Issue by PDXIII** [hoodiehq-archive/documentation#115]
You described the wrong ports in your tutorial.

You wrote:

```
WWW:    http://127.0.0.1:6040
Admin:  http://127.0.0.1:6041
CouchDB started: http://127.0.0.1:6042
```

But actually are:

```
WWW:    http://127.0.0.1:6004
Admin:  http://127.0.0.1:6005
CouchDB started: http://127.0.0.1:6006
```

It would be better if the images get changed, too

**Comment by badboy** [comment]
As mentioned in the IRC: the ports are not really wrong. Due to the way Hoodie picks new and free ports with multiple apps it can very well end up at 6040. 
It might be good too have a short explanation that ports might vary.

**Comment by zoepage** [comment]
Added note in b57b6a1bead6e2c9c75d2414bed3454f41b33a15

**Comment by PDXIII** [comment]
\o/

**Comment by badboy** [comment]
:dancer:
