### ISSUE TITLE
Responsive behaviour main navigation

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq-archive/documentation#128]
It seems like there are media queries missing.
![photo 04-02-15 16 57 37](https://cloud.githubusercontent.com/assets/1640079/6044510/fe388374-ac93-11e4-8d58-69c6df87d312.png)

**Comment by zoepage** [comment]
We should make the repo split happen soon @verpixelt :/

**Comment by verpixelt** [comment]
I'll bring my laptop with me on Saturday. Let's take a look at it together then, k?!

**Comment by zoepage** [comment]
Sounds perfect <3

**Comment by gr2m** [comment]
we are moving docs to http://hoodie.readthedocs.io/
