### ISSUE TITLE
Document hoodie.id()

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#13]
@gr2m:

We now have a new API: hoodie.id().

hoodie.id() generates and persists a random ID that is unique to the current user, independent of whether the user has an account or not. The id stored with every object in the createdBy attribute.

**Comment by zoepage** [comment]
Is this already documented somewhere?
cc @gr2m @svnlto @janl @espy @caolan

**Comment by gr2m** [comment]
Don't think so, but happy to help

**Comment by zoepage** [comment]
@gr2m done, right? :)

**Comment by gr2m** [comment]
@ola besides `hoodie.id()` a few other methods are missing:
- `hoodie.checkConnection()`
- `hoodie.isConnected()`
- `hoodie.open()`
- `hoodie.request()`
- `hoodie.extend()`

Shall i add document them together with `.id()`?

**Comment by zoepage** [comment]
You can add them here:
http://docs.hood.ie/en/techdocs/api/client/hoodie.html

Thanks a lot!
<3
