### ISSUE TITLE
Make links clickable in API docs

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/documentation#142]
E.g. ![screen shot 2015-02-20 at 15 01 42](https://cloud.githubusercontent.com/assets/11321/6287408/9448d0b0-b911-11e4-8cce-f885319c8d75.png)

the link to http://api.jquery.com/jquery.ajax/ is not clickable. I tried a few things locally, but none of them worked:

```
GitHub Style: <http://api.jquery.com/jquery.ajax/>
Markdown standard: [http://api.jquery.com/jquery.ajax/](http://api.jquery.com/jquery.ajax/)
Markdown footnote: [http://api.jquery.com/jquery.ajax/][1]
                                 [1]: http://api.jquery.com/jquery.ajax/

```

No dice whatsoever :/

Might have to do with the table thing we are using?

**Comment by zoepage** [comment]
the module broke the rendering of the tables. we need to do this by hand.
i'll take care of it :)
