### ISSUE TITLE
Typos and other Spelling Issues

### ISSUE THREAD

**Issue by quaxquax** [hoodiehq-archive/documentation#151]
Typo: "This will come mist handy" in the store.update() section of the docu (after first example).

Should be ""This will come in most handy".

Is there a wiki for the documentation under development?  Would be easiest to correct such simple mistakes on the fly while browsing the wiki.

**Comment by janl** [comment]
Well spotted! You can fix them here on GitHub all in the web UI: https://github.com/hoodiehq/documentation/tree/gh-pages/en

**Comment by zoepage** [comment]
thanks!
