### ISSUE TITLE
add instructions for deploying hoodie to OpenShift #22

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/documentation#17]
https://github.com/hoodiehq/hood.ie/issues/22

**Comment by zoepage** [comment]
@janl is this still a thing? ;)

**Comment by janl** [comment]
somebody wanted it, we haven’t done it yet

**Comment by zoepage** [comment]
it's from almost 1 year ago. do you think, it's still relevant? would like to close if not and reopen, if new request comes in?

**Comment by janl** [comment]
I don’t know, OpenShift is still around I presume. I don’t see value in closing feature requests, if the situation that asked for it didn’t change.
