### ISSUE TITLE
Hoodie Concepts → How Hoodie Works

### ISSUE THREAD

**Issue by tamacodechi** [hoodiehq-archive/documentation#175]
Not a huge issue, but I was thinking it would be good at the end of the Hoodie Concepts to not only link to the requirements page but also to the How It Works page for those who don't know. When we first looked at it, it was a little confusing to have to scroll all the way to the top just to find the link tucked away on the left.

:heart: from Team Tessie

**Comment by zoepage** [comment]
Very good catch! Thank you! :heart: 
@espy could you take care of this soon-ish? Would be awesome!
