### ISSUE TITLE
issues in API

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#177]
blue is saved just for links:
![bildschirmfoto 2015-07-10 um 11 22 34](https://cloud.githubusercontent.com/assets/562354/8615765/1907225a-26f6-11e5-9282-975672e26c64.png)

bulletpoints look strange:
![bildschirmfoto 2015-07-10 um 11 22 38](https://cloud.githubusercontent.com/assets/562354/8615766/1a88c926-26f6-11e5-9041-48dca8c67257.png)

**Comment by zoepage** [comment]
please make sure to add the same version to de folder and ping the people for ru/ && fr/ 
<3

**Comment by zoepage** [comment]
http://docs.hood.ie/en/techdocs/api/plugins/hoodie.email.html needs code highlighting

**Comment by zoepage** [comment]
padding-top of gray box looks too small. this is fixed by adding code highlighting
![bildschirmfoto 2015-07-10 um 11 27 42](https://cloud.githubusercontent.com/assets/562354/8615833/b563e19c-26f6-11e5-8eb5-dfdcbe2a78b1.png)
- http://docs.hood.ie/en/tutorials/map-app.html
- http://docs.hood.ie/en/techdocs/api/plugins/hoodie.email.html 
- http://docs.hood.ie/en/techdocs/api/plugins/hoodie.plugin.global.share.html
- http://docs.hood.ie/en/plugins/tutorial.html

it would be great, if the padding-top and the highlighting wouldn't depend on each other. otherwise we'll run into issues with that later. so please, separate in CSS.

**Comment by espy** [comment]
1. That is actually a link, so you can link to individual sections or bookmark/send them around.
2. Fixed! 
3. Totally forgot, will do later :o 
4. Wanted to do those after they'd been revised, but I can add highlighting quickly later, too.
5. Did you attach the wrong screenshot? There's no gray box in that one. Here's what they look like to me: 

![bildschirmfoto 2015-07-10 um 11 49 01](https://cloud.githubusercontent.com/assets/391124/8616218/b16609f0-26f9-11e5-8d03-ccfb1ddfce51.png)

**Comment by zoepage** [comment]
@espy oh noes, yes. the first two screenshots are mixed up. so sorry :(

**Comment by zoepage** [comment]
@espy 

> Did you attach the wrong screenshot? There's no gray box in that one. Here's what they look like to me:

No, you can see that in hoodie-global-shares for example

**Comment by espy** [comment]
Ah, I didn't touch the plugin pages at all, that's why. I'll go over them quickly later, but since they'll change completely soon, I didn't want to do to much. 

That extra big bullet point is pretty necessary when scrolling, as a visual marker where sections start. The headlines themselves aren't noticeable enough to structure the text properly. Any suggestions?

**Comment by zoepage** [comment]
It seems, it's working too well for me, because I get totally distracted :grin: 
What about an opacity of 0.5 for the bullet point and on hover 1.0?

**Comment by espy** [comment]
Fixed everything mentioned so far except the other language folders :)

**Comment by gr2m** [comment]
we are moving docs to http://hoodie.readthedocs.io/
