### ISSUE TITLE
Broken code example in plugin docs

### ISSUE THREAD

**Issue by schultyy** [hoodiehq-archive/documentation#182]
I was trying out the plugin tutorial (http://docs.hood.ie/en/plugins/tutorial.html) and noticed, that the following snippet doesn't work:

``` javascript
Hoodie.extend(function(hoodie) {
  hoodie.directMessages = {
    send: hoodie.task('directmessage').add,
    on: hoodie.task('directmessage').on // maybe not needed
  };
});
```

`hoodie.task('directmessage').add` does not exist. I got it working by using `hoodie.task('directmessage').start`.

**Comment by janl** [comment]
@espy can you have a look?

**Comment by espy** [comment]
Good find, thanks for reporting! I'll change it now. Plugins are being actively worked on right now, I'll try to be more up to date with changes in the future.
