### ISSUE TITLE
'originDb not defined' - in plugin documentation

### ISSUE THREAD

**Issue by schultyy** [hoodiehq-archive/documentation#183]
In http://docs.hood.ie/en/plugins/tutorial.html

``` javascript
  function addMessageCallback(error, message) {
    if(error){
        return hoodie.task.error(originDb, message, error);
    }
    return hoodie.task.success(originDb, message);
  };
```

there is no reference to `originDb`.

**Comment by janl** [comment]
@espy can you have a look?

**Comment by gr2m** [comment]
this is no longer relevant. We will create new docs for the new Plugin API soon on http://hoodie.readthedocs.io
