### ISSUE TITLE
No Subnav on Mobile makes docs hard to navigate

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/documentation#185]
I tried to look up the deployment docs on my phone and I didn’t know how to navigate there from docs.hood.ie:

![img_0853](https://cloud.githubusercontent.com/assets/11321/9406510/56851da4-4801-11e5-913f-7bad8c314ba1.PNG)
![img_0854](https://cloud.githubusercontent.com/assets/11321/9406511/576f208e-4801-11e5-9662-c3494f02e9f5.PNG)

**Comment by gr2m** [comment]
should be good now as we move to http://hoodie.readthedocs.io/en/latest/
