### ISSUE TITLE
[DEVELOPER HANDBOOK] Hoodie Configuration

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/documentation#192]
Prelude: This is supposed to go into the future _Developer Handbook_ section of the docs. I’ll put it here, so we won’t forget :)
# Hoodie Configuration

Hoodie has two separate concepts that pertain to configuration:
1. Hoodie Configuration
2. Application Configuration

Hoodie Configuration includes things like the TCP port, the `bind_address`, the path on the filesystem, where data is stored. [A full-ish list](https://github.com/hoodiehq/hoodie/blob/master/bin/help.txt). In short, things that define how Hoodie itself behaves, independent of the application that is built with Hoodie.

Application Configurations are things like email server settings, a stripe token, anything that pertains to the application itself. Some configuration settings are from Hoodie itself, plugins can add their own.

The main difference, aside from what they are for, is how they are handled. Hoodie Configuration can be passed into Hoodie, when it is started for the first time. All settings can be provided as _options_ in three different ways, that you can mix-and match any way you like:
1. As environment variables (`export HOODIE_FOO_BAR=value` TBD: actual value)
2. As .hoodierc files (TBD: EXAMPLE HERE)
3. As command line arguments: `npm run hoodie --bindAddress=192.168.1.2`

TBD: Example, sth like:

``` shell
export HOODIE_BIND_ADDRESS=192.168.1.2
npm run hoodie --port 2048 --data /tmp #just testing something
```

Changing any of these values requires you to restart Hoodie.

---

Application Configuration is managed via the Admin Dashboard. Settings can be changed while Hoodie it running and they go into effect immediately. The settings are stored in the Hoodie database.

This isn’t implemented yet, but we want to include it:

Sometimes it is useful to temporarily override an Application Configuration for e.g. debugging a local instance, and you want to use a different mail server setting. Then you can use the `.hoodierc` file or environment variables to temporarily override the Application Configuration that is defined in the Admin Dashboard and stored in the database.

**Comment by gr2m** [comment]
what configuration would you store in the database? Some settings should be the same across all environments (local, production, etc) like the app name, other settings like 3rd party service credentials should rather not be stored in database for security reasons.

**Comment by HipsterBrown** [comment]
For local development, the idea of a `.hoodierc` file that I could share across projects sounds wonderful. Even for onboarding new Hoodie users, giving a sample `.hoodierc` to download or copy/paste would be really simple. 

The environment variables are probably one of the best options for deploying Hoodie apps to staging or production servers. 

I definitely love the process of Application Configuration being done in the Admin Dashboard. This all looks great so far.

**Comment by gr2m** [comment]
Configuration can now be passed in as CLI arguments, environment variables, `.hoodierc` filed and defaults via the app’s pacakge.json, it’s documented in https://github.com/hoodiehq/hoodie#usage
