### ISSUE TITLE
HTML injection security hole in Tutorial example

### ISSUE THREAD

**Issue by mheiber** [hoodiehq-archive/documentation#196]
An example in the [tutorial](http://docs.hood.ie/en/tutorials/) has an HTML injection vulnerability:

``` js
var priority = collection[i].priority;
if(!priority){
  priority = "Normal";
}
$el.append(
  '<li data-id="' + collection[i].id + '">' +
    '<input type="checkbox"> <label>' + priority + ': ' +collection[i].title + '</label>' +
    '<input type="text" value="' + priority + ': ' +collection[i].title + '"/>' +
  '</li>'
);
```

`priority` and `title` are user-generated content and could include things like `<img onload="javascript:somethingMalicious() />`

I know that in this example, each user will see only his/her own content, but that could change in the future. It's _never_ a good idea to stick user input onto a page as raw HTML.
## Solutions:
1. Use `textContent`
2. Use templates
3. Escape HTML entities

(1) is probably best, in order to keep the tutorial simple and accessible. I'm happy to do a pull request.

**Comment by gr2m** [comment]
@mheiber oh wow, thanks Max, we'll look into it! I have it on my list for next week, I'll keep you posted

**Comment by gr2m** [comment]
@mheiber could you do the PR? That'd be super helpful :)
