### ISSUE TITLE
The navigation acts weird

### ISSUE THREAD

**Issue by Juni4567** [hoodiehq-archive/documentation#198]
When i toggle the navigation on my honor 3c android phone it not only alow me to tap scroll the screen but also makes the navigation to stop functioning.

**Comment by gr2m** [comment]
Thanks for reporting the issue Junaid! We are currently refactoring the implementation on the website, maybe the issue will be resolved by that already. I'll keep the issue open to check once the relaunch is ready

**Comment by gr2m** [comment]
we moved docs to http://hoodie.readthedocs.io/en/latest/ so this should no longer be a problem :) the docs.hood.ie domain will point to the new location soon
