### ISSUE TITLE
Figure out translations

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/documentation#22]

**Comment by zoepage** [comment]
any progress here yet?
@boennemann

**Comment by boennemann** [comment]
I wasn't aware that I should search for a solution here. If I should do so, even though @gr2m mentioned this isn't too relevant for 1.0 launch, please tell me so, along with some sort of specification/requirements to cover (:

**Comment by zoepage** [comment]
// cc @janl

**Comment by lenareinhard** [comment]
@boennemann @gr2m and I were talking about website (not docs) translations, and as Gregor and I agreed on, although we'll only launch with one language, we'll have to keep in mind the translations topic for the website relaunch. But this is off-topic here. So, regarding docs translations: there may be overlaps with the website translation regarding the technical implementation, but this will have to be figured out.

**Comment by zoepage** [comment]
+1
