### ISSUE TITLE
Glossary page is incomplete 

### ISSUE THREAD

**Issue by pmbanugo** [hoodiehq-archive/documentation#230]
The glossary of terms [page](http://docs.hood.ie/camp/hoodieverse/glossary.html) is incomplete. It should be made comprehensive and more terms defined. 

The TODO notes made in the public page should be removed and a list of terms to be added listed here while they're being defined and pushed to the live pages
- [x] Remove the todo placeholder

**Comment by gr2m** [comment]
few things that come to my mind
- Split CouchDB / PouchDB into separate sections
- [Hapi](http://hapijs.com/)
- Admin Dashboard
- Promises
- browserify

And maybe let’s add a link to https://github.com/hoodiehq/documentation/issues if a term is missing?

**Comment by pmbanugo** [comment]
adding that link on http://docs.hood.ie/camp/hoodieverse/glossary.html ? I don't think so

**Comment by pmbanugo** [comment]
Do these need to be added?
- Client
- Server
- Plugins

**Comment by pmbanugo** [comment]
#242 fixes some of the issues
