### ISSUE TITLE
hoodie-app-skeleton failed me ...

### ISSUE THREAD

**Issue by tgirod** [hoodiehq-archive/documentation#244]
I've tried to use hoodie-app-skeleton to start a new project.

```
$ hoodie new larp -t hoodiehq/hoodie-app-skeleton
$ cd larp
$ hoodie start

[...]

Version: 0.6.3 (node v4.6.1, npm 2.15.11, platform: linux)

[hoodie] Could not start hoodie.
```

verbose mode does not give more information about what went wrong. If I create a new default app without the template, everything works fine.

By the way, the doc links to zoepage/hoodie-app-skeleton, which might be outdated.

**Comment by gr2m** [comment]
hey @tgirod, the `hoodie-app-skeleton` repository and the Hoodie CLI are deprecated, we are currently working on a new Hoodie version that you better use to give it a try. Follow the instructions at https://github.com/hoodiehq/hoodie#setup, please let me know if you have any questions :)
