### ISSUE TITLE
Storage (Private)

### ISSUE THREAD

**Issue by boennemann** [hoodiehq-archive/documentation#34]
## Notes

https://github.com/hoodiehq/documentation/blob/master/techdocs/client/hoodie.store.md
## Status

go for it :shipit:

**Comment by zoepage** [comment]
https://github.com/hoodiehq/hood.ie/issues/70

**Comment by ghost** [comment]
I've documented every public function except for the decoratePromises, because I am not sure if this is only public by mistake or if it serves any deeper purpose.

Let's see if anything is missing or if we can pass this for english proofreading.

**Comment by gr2m** [comment]
we will remove the decoratePromises feature from hoodie.js, it didn't turn out to be useful, but adds quite some complexity and probably performance impacts. So just leave it out from the docs.

**Comment by lewiscowper** [comment]
ping me on a ticket if you want it proofreading. :+1: Nice work getting it documented too.

**Comment by zoepage** [comment]
@snnd how is the status here? is hoodiehq/hood.ie#70 solved?

**Comment by janl** [comment]
Added my review as a pull request: https://github.com/hoodiehq/documentation/pull/70

**Comment by boennemann** [comment]
Please merge/review #71 before merging ~~this one~~ #70.
