### ISSUE TITLE
Document plugin global shares

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/documentation#4]
https://github.com/hoodiehq/hoodie-plugin-global-share/

**Comment by gr2m** [comment]
I'll look into it tomorrow

**Comment by gr2m** [comment]
is documenting the plugin in its README sufficient? Is there something existing I can take as blueprint?

**Comment by janl** [comment]
Readme is fine for now, the docs team can take it from there (cc @snnd @tenmilestereo)
