### ISSUE TITLE
Hoodie + Cordova/PhoneGap

### ISSUE THREAD

**Issue by boennemann** [hoodiehq-archive/documentation#42]
One question that often arises in IRC is if there's something to be considered when using hoodie together with PhoneGap.

As far as I can remember the answer has always been a simple _no_. Is there anything to add here or can we just put this in the [FAQ document](https://github.com/hoodiehq/documentation/wiki/The-Hoodie-FAQ-%E2%80%93%C2%A0Work-in-Progress) right away?

**Comment by gr2m** [comment]
I'd say yes. Just add a simple _no_, we can change it later in case anyone runs into trouble. But I couldn't think of any.

**Comment by boennemann** [comment]
https://github.com/hoodiehq/documentation/wiki/The-Hoodie-FAQ-%E2%80%93%C2%A0Work-in-Progress#is-there-anything-to-be-considered-when-using-hoodie-together-with-phonegapcordova

**Comment by quangv** [comment]
Just to clarify, does hoodie work with PhoneGap/Cordova?

(Not sure if _no_ means, "Yes, it _just_ works" or "No, it does not work.")

Thanks!

Edited:

https://github.com/hoodiehq/faq/issues/19 - found this

ah, I guess it _just_ works :)
