### ISSUE TITLE
HTTPS connection?

### ISSUE THREAD

**Issue by cathyhuis** [hoodiehq-archive/documentation#44]
Is it possible to use a HTTPS connection for Hood.ie? Or does Hood.ie encrypt the passwords anyway?

**Comment by janl** [comment]
Hoodie does not itself do HTTPS, we recommend using HAProxy for that. See my-first-hoodie/deployment.md for details

**Comment by zoepage** [comment]
Is the answer enough for you @cathyhuis? :)
So we could close the issue ;)
