### ISSUE TITLE
Hoodie Magic

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#45]
- [x] Promises
- [x] noBackend
- [x] CouchDB structure

**Comment by gr2m** [comment]
Goes Offline First in here, too?

**Comment by zoepage** [comment]
no, this is hoodie concepts

**Comment by lenareinhard** [comment]
- noBackend + CouchDB are in here: https://github.com/hoodiehq/documentation/blob/gh-pages/tutorials/how-hoodie-works-behind-the-magic.md
- Promises are missing.
