### ISSUE TITLE
Document custom plugin views in pocket

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#5]

**Comment by janl** [comment]
cc https://github.com/hoodiehq/pocket/issues/45

**Comment by zoepage** [comment]
almost done with https://github.com/hoodiehq/hoodie-plugin-template right?

**Comment by janl** [comment]
@zoepage what I imagine is a guide like espy/hoodie-plugin-guide (in fact, I imagine it as a section of that guide) that goes through all the steps one needs to do to write a pocket plugin.

**Comment by espy** [comment]
So does Ola's update of the Plugin Tutorial (https://github.com/hoodiehq/hoodie-plugin-tutorial) plus the UIKit guide (hoodiehq.github.io/hoodie-pocket-UIKit/) satisfy this issue? We're still missing the hoodieAdmin bits, but that's up for a rewrite anyway, so I'm not sure.

**Comment by janl** [comment]
Looks good to me!
