### ISSUE TITLE
store.validate() Notes are unclear

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/documentation#54]
> id is a combination of both, formatted as "type/id".

Not sure what you mean by this?

**Comment by ghost** [comment]
By this I wanted to express, that die object id, internally is a combination of store name and random object id. Any better suggestions on that?

**Comment by gr2m** [comment]
the combination of type & id to a "type/id" key is internal only, I would not document that at all.

**Comment by zoepage** [comment]
+1 on not documenting that.

**Comment by ghost** [comment]
removed with 7012d5ad91221465eac07ad83ebf6fb9a5ced749
