### ISSUE TITLE
Leave out the BAD VARIATION example of hoodie.store.findOrAdd

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/documentation#56]
The code is not correct as is, it's even more complex because of the promise handling. I'd suggest to remove the code altogether, it probably is more confusing than helpful?

**Comment by zoepage** [comment]
Cc @snnd

**Comment by ghost** [comment]
Leaving this part out would be fine with me. Any other opinions on that anyone?

**Comment by zoepage** [comment]
+1

**Comment by ghost** [comment]
removed with b877929b7d3dfa0a884ae4e74cde61ae7338ad63
