### ISSUE TITLE
Document payments

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#6]

**Comment by lenareinhard** [comment]
see #61 and #39

**Comment by zoepage** [comment]
this issue should be remembered as long as it is still one of the milestones... so, it stays open! :)

**Comment by zoepage** [comment]
I've assigned @gr2m to this, bc he is on the development of the plugin. So it will be remembered ;)

**Comment by gr2m** [comment]
is this needed for the new website?

**Comment by zoepage** [comment]
we will need this later on!

**Comment by janl** [comment]
just FYI: payments are nowhere near done yet, sorry.
