### ISSUE TITLE
Document contributor onboarding

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq-archive/documentation#65]
moved to https://github.com/hoodiehq/documentation/blob/gh-pages/tutorials/contributor-onboarding.md

**Comment by lenareinhard** [comment]
sources for further reading:
-  http://www.mediawiki.org/wiki/Project:New_contributors
-  http://www.mediawiki.org/wiki/How_to_contribute
-  page 19 (research-based model) https://www.right.com/thought-leadership/research/shrm-foundations-effective-practice-guidelines-series-onboarding-new-employees-maximizing-success-sponsored-by-right-management.pdf
-  http://blog.smartbear.com/programming/14-ways-to-contribute-to-open-source-without-being-a-programming-genius-or-a-rock-star/
-  http://de.slideshare.net/LewisCowper/onboarding-contributors-to-your-oss-project?ref=http://lewiscowper.org/talks.html
-  for devs: http://codefirefox.com/

**Comment by lenareinhard** [comment]
reviewed recent changes, added further content (see https://github.com/hoodiehq/documentation/commit/ca33039f13d045b211cfe1f7f243d26a9b3ea2a0 ). Imo, the doc is ready to go for its first iteration. Will (have to) be worked on frequently anyway. 

Thus: suggestion to close this issue and mark as done. cc @zoepage

**Comment by zoepage** [comment]
thank you @ffffux <3
