### ISSUE TITLE
appconfig plugin

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#67]

**Comment by gr2m** [comment]
Happy to help here, just let me know where and how :)

It might be as simple as copy / pasting content from the README's of https://github.com/hoodiehq/hoodie-plugin-appcache & https://github.com/gr2m/appcache-nanny/

**Comment by zoepage** [comment]
@gr2m this is not about the appcache, it's about the core plugin: https://www.npmjs.com/package/hoodie-plugin-appconfig
