### ISSUE TITLE
cheatsheet

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#72]
include cheatsheet in documentation.
- all the methods at one place are listed
- links to right place in documentation are provided like here
  http://v2.getkirby.com/docs/cheatsheet

**Comment by brianshumate** [comment]
[This gist](https://gist.github.com/brianshumate/3431d40711365b2a3141) mostly meets the goals of this issue, and was based on the existing [PDF cheatsheet](http://hood.ie/dist/presentations/hoodie-cheat-sheet.pdf). 

However, there are still a few minor points to work out with it:
- It is not especially attractive with GitHub's default table styling
- The in page anchor links from the table of contents work for me while previewing the content (i.e. in Mou editor), but they do not work in the gist itself
- I cannot find the actual API documentation to which each linked element should link
- I am unsure of where this should live in the current documentation structure

I'd be happy to improve it and contribute with feedback on the above points. :)

**Comment by zoepage** [comment]
@brianshumate sorry for getting back so late. your gist was a huge help! thanks for that!!! :+1: 
You can find the cheatsheet in the footer of the docs. 

thanks <3
