### ISSUE TITLE
hoodie.account.md has unresolved merge conflicts

### ISSUE THREAD

**Issue by passy** [hoodiehq-archive/documentation#76]
There are a couple of `<<<<<<< HEAD`s left in the account docs at the moment. :)

https://github.com/hoodiehq/documentation/blob/6eb871cc0d185a6cd48a6941f0c40ea2c9a8f390/techdocs/api/client/hoodie.account.md

**Comment by zoepage** [comment]
yes, sorry, will fix that asap :)
