### ISSUE TITLE
Hoodie Cheat Sheet fixes

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq-archive/documentation#77]
Cheat Sheet basis is here: https://github.com/hoodiehq/hoodie.js/blob/master/CheatSheet.md
- [x] '.addOrUpdate(type, id, properties' -> correct command is '.UpdateOrAdd(type, id, properties'
- [x] Hoodie Store: .on is missing (at least that's what the workshop attendees said :) )

**Comment by zoepage** [comment]
If you know which one, please assign the task to me and I'll finish it asap.

**Comment by lenareinhard** [comment]
added above. Thanks, @zoepage!

**Comment by zoepage** [comment]
Hoodie.store.on is in the 3rd column. They might not have seen it :grin: 
Fixed the second one. 

Where should I put the pdf and also the indd file?

**Comment by lenareinhard** [comment]
awesome! 
Suggestion: 
- I'll add the pdf as a direct download to the website
- can we also upload the pdf to the /documentation/tutorials folder? (if it makes sense there?)
