### ISSUE TITLE
Finish "How to give a Hoodie Workshop"-content + running order

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq-archive/documentation#78]
Draft is here: https://docs.google.com/a/thehoodiefirm.com/document/d/1HijseqxQvPO9auzBuobPvuzv5Y3XQaf_g0u1fhJ3jvo/edit# 
It's done in huge parts, but there are a few important things missing (see missing content + comments)

**Comment by lenareinhard** [comment]
moved draft to GitHub https://github.com/hoodiehq/documentation/blob/gh-pages/tutorials/hosting-a-hoodie-workshop.md

**Comment by zoepage** [comment]
the document now lives here: http://docs.hood.ie/community/hosting-a-hoodie-workshop.html

I added content. If you @ffffux think it's ok, please close the issue. thank you :)

**Comment by lenareinhard** [comment]
thanks, @zoepage <3
