### ISSUE TITLE
Development/Testing in hoodiehq/hoodie.js#master

### ISSUE THREAD

**Issue by ghost** [hoodiehq-archive/documentation#85]
I am missing a straight forward description of how to get started with hoodiehq/hoodie.js master. Usually, when I want to contribute to a project, I just fork their repository, use it as an npm in an isolated project and file a pull request

Since hoodie apps, are a kindof composed boilerplate via hoodie-cli, I miss a straight forward guide, that tell's me how to get started with a setup to contribute code. Is there anybody who can just drop some lines on this topic? @gr2m @janl @svnlto @zoepage @boennemann?

For the later I would like to create a polished version of the guide for hoodiehq/documentation.

Regards,
Dennis

**Comment by zoepage** [comment]
Hey @snnd!
Thanks for your help. If you would like to, we can discuss this topic later and document it here?

Or do you want to get started right away?

**Comment by ghost** [comment]
No hurry. I just recognized a lack of straight forward documentation when I was about to test a bugfixed issue in hoodiehq/hoodie.js#master.

I appreciate your help on this later today. :) :+1:

**Comment by zoepage** [comment]
Cool! 

It anyone else wants to add some information, please feel free!

**Comment by gr2m** [comment]
I think if a unit test is enough, you can simply
1. git clone hoodie.js
2. npm install
3. grunt test

If you want to test the changes with a Hoodie app, `npm link /path/to/hoodie.js` in your app folder, then add `hoodie.hoodie.js` to your package.json

```
"hoodie": {
    "plugins": [
      "hoodie-plugin-appconfig",
      "hoodie-plugin-email",
      "hoodie-plugin-users",
      ...
    ],
    "hoodiejs": "node_modules/hoodie/src/hoodie.js"
  },
```

Simply reloading the app should trigger hoodie-server to re-bundle the `/_api/_files/hoodie.js` file, now using your local fork.

Hope that helps?
